### ISSUE TITLE
featureDetectionClass openCV Error: Assertion failed

### ISSUE THREAD

**Issue by shaikhtariq11** [BloodAxe/OpenCV-Tutorial#10]
OpenCV Error: Assertion failed (type == src2.type() && src1.cols == src2.cols && (type == CV_32F || type == CV_8U)) in batchDistance, file /Users/vp/work/opencv/modules/core/src/stat.cpp, line 3208
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/vp/work/opencv/modules/core/src/stat.cpp:3208: error: (-215) type == src2.type() && src1.cols == src2.cols && (type == CV_32F || type == CV_8U) in function batchDistance

Getting this error when i move my device away from the image.
Below is Line where crashing:
 matcher->knnMatch(descriptors1,
                      descriptors2,
                      matches1, // vector of matches (up to 2 per entry)
                      2);        // return 2 nearest neighbours

**Comment by BloodAxe** [comment]
Fixed in new version of OpenCV that now comes with OpenCV-Tutorial.
