### ISSUE TITLE
Lexical or preprocessor error 

### ISSUE THREAD

**Issue by akshea** [BloodAxe/OpenCV-Tutorial#11]
Hi,
Please some one help on the below issue to solve
I am getting lexical or preprocessor error string not found in SampleOptions.h file,

 if i set the Build settings->compiler source as -> Objective C

if i set the if i set the Build settings->compiler source as -> According to file type, then i am getting 

Semantic Issue : VideoTracking.hpp:53:9: No type named 'BFMatcher' in namespace 'cv'
lexical or preprocessor error: CameraCalibrationAlgorithm.h:5:10: 'array' file not found
Semantic Issue : FeatureDetectionSample.h:41:17: No member named 'AKAZE' in namespace 'cv'

**Comment by BloodAxe** [comment]
Thanks for report. Will take a look on it.

**Comment by BloodAxe** [comment]
Sorry I could not reproduce your issue. Please ensure you are on master branch. If you cloned old version of this project, please pull all latest changes and rebuilt it.
